# Vi-mode
setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"

# Bind
bind -n M-r source-file ~/.config/tmux/tmux.conf \; run '~/.tmux/plugins/tpm/tpm' \; refresh-client -S

bind -n C-s choose-session

bind -n M-Enter new-window
bind -n M-q kill-window
bind -n C-q kill-pane
bind -n M-d detach

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

bind -n C-v split-window -v
bind -n C-h split-window -h

bind -n C-M-h resize-pane -L 5
bind -n C-M-l resize-pane -R 5
bind -n C-M-k resize-pane -U 5
bind -n C-M-j resize-pane -D 5

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

run '~/.tmux/plugins/tpm/tpm'

#Theme
set -g status on
set -g status-interval 5
set -g status-justify left
set -g status-left-length 60
set -g status-right-length 120

set -g @bg "#2a0f16"
set -g @fg "#ffd1dc"
set -g @accent "#ff2e88"
set -g @dim "#3a1620"

set -g status-style "bg=#2a0f16,fg=#ffd1dc"

set -g status-left "\
#[fg=#2a0f16,bg=#ffd1dc,bold]   #S \
#[fg=#ffd1dc,bg=#2a0f16] "

set -g window-status-separator " "

set -g window-status-format "\
#[fg=#ffd1dc] #I › #W "

set -g window-status-current-format "\
#[fg=#2a0f16,bg=#ff2e88]\
#[fg=#2a0f16,bg=#ff2e88,bold] #I › #W \
#[fg=#ff2e88,bg=#2a0f16]"

set -g pane-border-style "fg=#3a1620"
set -g pane-active-border-style "fg=#ff2e88"

set -g message-style "bg=#3a1620,fg=#ffd1dc"
set -g message-command-style "bg=#2a0f16,fg=#ff2e88"

set -g status-right "\
#[fg=#3a1620]│ \
#[fg=#ffd1dc] #(whoami) \
#[fg=#3a1620]│ \
"

set -g mode-style "bg=#3a1620,fg=#ff2e88"

# Env
set -g mouse on

set -g escape-time 0
set -g base-index 1
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ',xterm-kitty:Tc'

set -g renumber-windows on
set -g detach-on-destroy off
set -g history-limit 100000
